"use client";

import { ArrowUpRight, Download, Printer, Save, Sparkles } from "lucide-react";
import { metricCodes, type CaseDecision, type CaseEvaluation, type CaseRecommendation, type CityCase } from "@/domain/city-case";
import { metricDefinitions } from "@/data/astana-catalog";
import { formatDelta, formatScore } from "@/components/simulation/presentation";
import styles from "./city-lab.module.css";

export type Narration = { status: "ready"; content: { summary: string; strengths: string[]; risks: string[]; tradeoffs: string[] } } | { status: "unavailable"; reason: string };
type Props = { cityCase: CityCase; decisions: CaseDecision[]; evaluation: CaseEvaluation; narration: Narration | null; analyzing: boolean; onAnalyze: () => void; onSave: () => void; onApply: (recommendation: CaseRecommendation) => void };

export function CaseReport({ cityCase, decisions, evaluation, narration, analyzing, onAnalyze, onSave, onApply }: Props) {
  const { result } = evaluation;
  const weakest = result.districts.find((district) => district.districtId === evaluation.equity.weakestDistrictId);
  function exportReport() {
    const blob = new Blob([JSON.stringify({ exportedAt: new Date().toISOString(), case: cityCase, decisions, evaluation, narration }, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a"); link.href = url;
    link.download = `city-lab-${cityCase.id.replace(/[^a-zA-Z0-9-]/g, "_")}-8q.json`;
    link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  return <section className={styles.report} aria-labelledby="report-title">
    <div className={styles.sectionHeading}><div><span className={styles.eyebrow}>03 / РЕЗУЛЬТАТ</span><h2 id="report-title">Что изменится в городе</h2></div><span className={styles.tag}>{cityCase.city.horizonQuarters} кварталов</span></div>
    <div className={styles.scoreGrid}>
      <div className={styles.scoreCard}><span>Итоговый индекс · Score / AQoL</span><strong data-testid="final-score">{formatScore(result.finalAqol)}</strong><p>{formatDelta(result.finalAqol - result.baselineAqol)} к исходным {formatScore(result.baselineAqol)}</p></div>
      <div className={styles.metricCard}><span>Самый слабый район</span><strong>{weakest?.districtName ?? "—"}</strong><p>Качество D: {formatScore(result.finalWeakest)}</p></div>
      <div className={styles.metricCard}><span>Критические показатели &lt; 40</span><strong>{result.criticalCount}<small> / 50</small></strong><p>До решений: {result.baselineCriticalCount}. Каждый даёт −1 к Score.</p></div>
    </div>
    <section className={styles.panel}><h3>Откуда берётся результат</h3><div className={styles.formula}><div><span>Среднее по населению</span><strong>{formatScore(result.finalAverage)}</strong><small>× 0,7</small></div><span>+</span><div><span>Слабейший район</span><strong>{formatScore(result.finalWeakest)}</strong><small>× 0,3</small></div><span>−</span><div><span>Критические показатели</span><strong>{result.criticalCount}</strong><small>строго ниже 40</small></div><span>=</span><div><span>Score / AQoL</span><strong>{formatScore(result.finalAqol)}</strong><small>округлено для показа</small></div></div><p className={styles.note}>Качество района — сумма 10 показателей с фиксированными весами. Среднее города учитывает доли населения. Отрицательные эффекты также масштабируются по лагу; округляется только отображение.</p></section>
    <section className={styles.panel}><h3>Пять районов · десять показателей</h3><p className={styles.muted}>Итоговые значения и изменение к исходному уровню. Меньше 40 — критическое состояние.</p><div className={styles.tableScroll}><table className={`${styles.table} ${styles.metricTable}`}><caption className={styles.srOnly}>Итоговые показатели районов</caption><thead><tr><th>Район</th>{metricCodes.map((code) => <th key={code} title={metricDefinitions[code].name}>{code}<small>{formatScore(metricDefinitions[code].weight * 100)}%</small></th>)}<th>Качество D</th></tr></thead><tbody>{result.districts.map((district) => <tr key={district.districtId}><th>{district.districtName}<small>{formatScore(district.populationShare * 100)}% населения</small></th>{metricCodes.map((code) => <td key={code} data-critical={district.final[code] < 40}><span>{formatScore(district.final[code])}{district.final[code] < 40 ? " !" : ""}</span><small>{formatDelta(district.realizedDelta[code])}</small></td>)}<td><strong>{formatScore(district.quality)}</strong><small>{formatDelta(district.quality - district.baselineQuality)}</small></td></tr>)}</tbody></table></div><details className={styles.metricLegend}><summary>Расшифровка показателей и весов</summary><dl>{metricCodes.map((code) => <div key={code}><dt>{code} · {metricDefinitions[code].name} · {formatScore(metricDefinitions[code].weight * 100)}%</dt><dd>{metricDefinitions[code].description}</dd></div>)}</dl></details></section>
    <div className={styles.reportColumns}><section className={styles.panel}><h3>Неравенство между районами</h3><div className={styles.sensitivity}><div><strong>{formatScore(evaluation.equity.gapBefore)}</strong><span>Разрыв до</span></div><div><strong>{formatScore(evaluation.equity.gapAfter)}</strong><span>Разрыв после</span></div><div><strong>{formatDelta(evaluation.equity.gapAfter - evaluation.equity.gapBefore)}</strong><span>Изменение</span></div></div><p className={styles.note}>Разница между самым высоким и самым низким качеством района. Снижение разрыва не обязательно означает рост всех показателей.</p></section><section className={styles.panel}><h3>Масштаб и ресурсы</h3><div className={styles.reportTotals}><span>Бюджет: <b>{result.spent} / {result.budget}</b></span><span>Осталось: <b>{result.remaining}</b></span></div><p className={styles.note}>Затронутые районы охватывают <b>{formatScore(evaluation.reach.populationShare * 100)}% населения</b> модели. Это доля жителей районов, а не число фактических получателей пользы.</p><p className={styles.note}>Данные заданы для симулятора. Это учебный сценарий, а не эмпирический прогноз развития города.</p></section></div>
    <section className={styles.panel}><h3>Реализация выбранных мер</h3><div className={styles.tableScroll}><table className={styles.table}><caption className={styles.srOnly}>Стоимость и доля реализации мер за восемь кварталов</caption><thead><tr><th>Мера</th><th>Где действует</th><th>Стоимость</th><th>Лаг</th><th>Реализовано</th><th>Вклад после лага</th></tr></thead><tbody>{result.contributions.map((item) => <tr key={item.measureId}><th>{item.measureId} · {item.measureName}</th><td>{item.districtIds.length === cityCase.city.districts.length ? "Весь город" : item.districtIds.map((id) => cityCase.city.districts.find((district) => district.id === id)?.name ?? id).join(", ")}</td><td>{item.cost}</td><td>{item.lagQuarters} кв.</td><td>{formatScore(item.realizedFraction * 100)}%</td><td>{Object.entries(item.effects).map(([code, value]) => `${code} ${formatDelta(value!)}`).join(", ")}</td></tr>)}</tbody></table></div><p className={styles.note}>Доля реализации = (8 − лаг) / 8. Все изменения складываются, затем показатели один раз ограничиваются диапазоном 0–100.</p>{result.synergies.length > 0 && <div className={styles.synergies}><h4>Сработавшие синергии</h4>{result.synergies.map((item) => <p key={`${item.measureIds.join("-")}-${item.districtId}`}>{item.measureIds.join(" + ")} · {cityCase.city.districts.find((district) => district.id === item.districtId)?.name}: {Object.entries(item.effects).map(([code, value]) => `${code} ${formatDelta(value!)}`).join(", ")}</p>)}<small>Фиксированные бонусы синергии применяются без масштабирования по лагу.</small></div>}</section>
    {evaluation.warnings.length > 0 && <div className={styles.warning}><h3>Учитывайте ограничения</h3><ul>{evaluation.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></div>}
    <section className={styles.panel}><h3>Варианты улучшения плана</h3><p className={styles.muted}>Реально пересчитанные замены одной меры, с бюджетом и всеми ограничениями. Каждый вариант независим. После применения нужен новый расчёт.</p>{evaluation.recommendations.length === 0 ? <p>Допустимых улучшений одиночной заменой не найдено.</p> : <div className={styles.recommendations}>{evaluation.recommendations.map((item) => <div key={`${item.replaceMeasureId}-${item.decision.measureId}-${item.decision.districtId}`}><div><span className={styles.tag}>{formatDelta(item.aqolGain)} Score</span><h4>{item.replaceMeasureId} → {item.decision.measureId} · {cityCase.city.measures.find((measure) => measure.id === item.decision.measureId)?.name}</h4><p>{item.decision.districtId ? cityCase.city.districts.find((district) => district.id === item.decision.districtId)?.name : "Весь город"}</p><p>{item.explanation}</p><small>Изменение стоимости {formatDelta(item.capitalChange)} ед.</small></div><button className={`${styles.secondaryButton} ${styles.noPrint}`} onClick={() => onApply(item)}>Применить <ArrowUpRight size={16} aria-hidden="true" /></button></div>)}</div>}</section>
    <section className={styles.aiPanel}><div className={styles.sectionHeading}><div><span className={styles.eyebrow}>ОБЪЯСНЕНИЕ, А НЕ РАСЧЁТ</span><h3><Sparkles size={19} aria-hidden="true" /> AI-разбор</h3></div><button className={`${styles.secondaryButton} ${styles.noPrint}`} onClick={onAnalyze} disabled={analyzing}>{analyzing ? "Формируем разбор…" : narration ? "Повторить разбор" : "Объяснить результат"}</button></div><div aria-live="polite">{!narration && <p>Модель объяснит рассчитанные факты, риски и компромиссы. Численные результаты уже доступны и не зависят от AI.</p>}{narration?.status === "unavailable" && <p role="status">AI-разбор недоступен: {narration.reason}</p>}{narration?.status === "ready" && <><p>{narration.content.summary}</p><div className={styles.narrationGrid}>{([['Сильные стороны', narration.content.strengths], ['Риски', narration.content.risks], ['Компромиссы', narration.content.tradeoffs]] as const).map(([label, items]) => <div key={label}><h4>{label}</h4><ul>{items.map((item, index) => <li key={index}>{item}</li>)}</ul></div>)}</div></>}</div></section>
    <div className={`${styles.actions} ${styles.noPrint}`}><button className={styles.primaryButton} onClick={onSave}><Save size={16} aria-hidden="true" /> Сохранить сценарий</button><button className={styles.secondaryButton} onClick={exportReport}><Download size={16} aria-hidden="true" /> JSON</button><button className={styles.secondaryButton} onClick={() => window.print()}><Printer size={16} aria-hidden="true" /> Печатный отчёт</button></div>
    <p className={styles.note}>Кейс {cityCase.id} · модель {cityCase.version} · горизонт {cityCase.city.horizonQuarters} кварталов. Формула Score = 0,7 × D_avg + 0,3 × min(D) − N_crit.</p>
  </section>;
}
